name: 'Increment Package.json Version'
description: 'Bumps version in package.json based on user defined PR labels'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  default_branch:
    description: 'default branch of the project. i.e main or master'
    required: false
    default: 'remotes/origin/master'
  github_token:
    description: 'github token'
    required: true
  source:
    description: 'what text shall we match against the following semver triggers, possible values: title, label'
    required: false
    default: 'title'
  pull_request:
    description: 'PR number, if not given, context.issue.number is used'
    required: false
  major_pattern:
    description: 'regexp pattern used to trigger major bump against input source'
    required: false
    default: /^(major|release)/i
  minor_pattern:
    description: 'regexp pattern used to trigger minor bump against input source'
    required: false
    default: /^feat/i
  patch_pattern:
    description: 'regexp pattern used to trigger patch bump against input source'
    required: false
    default: /^fix/i
  package_json_path:
    description: 'package.json location from where we determine current version, package.json in repo root by default'
    required: false
  previous_version:
    description: 'Previous version to be used, which would override any version value from package.json'
outputs:
  previous_version:
    description: 'Previous version in package.json for the actual branch'
  previous_version_master:
    description: 'Previous version in package.json for the master branch'
  new_version:
    description: 'New version in package.json'
runs:
  using: 'node12'
  main: 'dist/index.js'
