name: Approve PR

on:
  # Try merging a pull request when it is approved.
  pull_request_review:
    types:
      - submitted
  push:
    branches:
      - 'master'

jobs:
  tagging:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'

    steps:
    - uses: actions/checkout@v2

    - run: |
        npm install

    - uses: finnoconsult/github-actions-package-bump-version@feature/initial
      id: bumpVersion
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        package_json_path: 'package.json'
        source: title
    - run: |
        echo "PR ${{github.event.pull_request.number}}, ${{github.event_name}}: ${{github.event.review.state}} on ${{github.ref}} (${{github.sha}})"
        echo "old version ${{steps.bumpVersion.outputs.previous_version}}, new version ${{steps.bumpVersion.outputs.new_version}}"


    - uses: EndBug/add-and-commit@v7
      if: steps.bumpVersion.outputs.previous_version != steps.bumpVersion.outputs.new_version
      with:
        message: 'CI: bump package version, affer stale approvals by ${{github.event.review.user.login}} [skip ci]'
        add: '*'

    # - uses: hmarr/auto-approve-action@v2.0.0
    #   if: steps.bumpVersion.outputs.previous_version != steps.bumpVersion.outputs.new_version
    #   with:
    #     github-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: reitermarkus/automerge@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        merge-method: rebase
        do-not-merge-labels: never-merge
        pull-request: ${{ github.event.inputs.pull-request }}
        dry-run: true