name: build dist content on every push

on:
  push:
    # branches:
    #   - 'maser' # WHEN CODE GETS MERGED INTO master branch (ALSO DIRECT PUSHES)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # STAGING release & tag
    - uses: dev-drprasad/delete-tag-and-release@v0.1.3
      with:
        delete_release: true
        tag_name: 'release/staging'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Bump version and push tag
      id: tag_release
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        custom_tag: 'release/staging'
        append_to_pre_release_tag: ''
        release_branches: development,staging,production
        create_annotated_tag: true
    - run: |
        npm run build
        git status

    - name: Commit changelog file
      uses: swinton/commit@v2.x
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          dist/index.js
          dist/index.js.map
          dist/sourcemap-register.js
          dist/package.json
        commit-message: 'CI: add build files [skip ci]'
        ref: refs/heads/master
